### ISSUE TITLE
Switch to IORedis instead of promisify

### ISSUE THREAD

**Issue by rileyai-dev** [TheDeveloper/node-redis-script#1]
@TheDeveloper I use the excellent [warlock](https://github.com/TheDeveloper/warlock) which relies on this library (or more accurately the deprecated scripty library) and I'd like to move away from node-redis since it doesn't support promises.

I can see that this library uses promisify and I think that it should directly use IORedis instead. That way, we could easily change the warlock client as well and have a cleaner code.

**Comment by TheDeveloper** [comment]
hi @grapevineai thank you for your thoughts!

I agree, IORedis would certainly make the code cleaner.

In terms of connecting to redis - would you still want to give it a client? Or instead, a host/port combo to connect to, and internally it would use IORedis?

**Comment by rileyai-dev** [comment]
@TheDeveloper Actually I have already created new projects for our internal use: https://github.com/grapevine-ai/warlock-script and https://github.com/grapevine-ai/redis-warlock

Let me know what you think...the idea was to eventually make warlock compatible with promises.

**Comment by TheDeveloper** [comment]
ioredis now supported in [v2.0.0](https://github.com/TheDeveloper/node-redis-script/releases/tag/v2.0.0)
